application:
  name: user-service
server:
  port: 8081

spring:
  datasource:
    driverClassName: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/user-db
    username: user-db-user
    password: user-db-password
  jpa:
    hibernate.ddl-auto: update
    generate-ddl: true
    show-sql: true
app:
  jwt-secret: daf66e01593f61a15b857cf433aae03a005812b31234e149036bcc8dee755dbb
  jwt-expiration-milliseconds: 604800000

management.endpoints.web.exposure.include: "*"